# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Girke Lab
tagline:             'Site'
description:         'Girke Lab Site'
url:                 http://tgirke.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Thomas Girke
  url:               http://girke.bioinformatics.ucr.edu
  email:             thomas.girke@ucr.edu

# Custom vars
version:             Lanyon v1.0.0
